Improve the key/identifier/id situation
buildkite/pipeline-schema pull request #92
Opened 2024-11-24 03:09 UTC by thejcannon

- Make `id` and `identifier` use the `key` definition
- Add a "not UUID" regex to the `key` definitions
- (Happy to undo) mark `id` as `deprecated`
- Shuffled the order so `id`/`identifier` are after `key`

Fixes #76

2024-11-24 03:09 UTC, thejcannon commented on schema.json
> +    },f
```suggestion
    },
```

2024-11-24 12:51 UTC, thejcannon commented
FWIW if you like the `$ref` thing, it can/should be used for other aliases. Happy to put up a PR.

2024-11-27 04:12 UTC, DrJosh9000 requested changes

2024-11-27 04:12 UTC, DrJosh9000 commented on schema.json
> +          "deprecated": true,
```suggestion
          "deprecated": true
```

2024-11-27 04:12 UTC, DrJosh9000 commented on schema.json
> +          "$ref": "#/definitions/triggerStep/proprties/key"
```suggestion
          "$ref": "#/definitions/triggerStep/properties/key"
```

2024-11-27 22:33 UTC, DrJosh9000 approved these changes
LGTM

2024-11-27 22:33 UTC, merged